name: Shared - Danger JS
on:
  pull_request:
    types: [labeled, unlabeled, opened, reopened, edited, synchronize]

jobs:
  build:
    name: Danger JS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Danger
        uses: danger/danger-js@13.0.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: "--dangerfile duckduckgo/danger-settings/org/allPRs.ts@dominik/singletons"
