name: iOS - Shared Web Tests

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *' # Run at 2 AM UTC
  workflow_call:
    secrets:
      APPLE_API_KEY_BASE64:
        required: true
      APPLE_API_KEY_ID:
        required: true
      APPLE_API_KEY_ISSUER:
        required: true
      ASANA_ACCESS_TOKEN:
        required: true
      MATCH_PASSWORD:
        required: true
      SSH_PRIVATE_KEY_FASTLANE_MATCH:
        required: true

jobs:
  shared-web-tests:
    name: Shared web tests

    runs-on: macos-15
    timeout-minutes: 30
    steps:
    - name: Check out the code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Select Xcode
      uses: ./.github/actions/select-xcode-version

    - name: Checkout shared web tests
      uses: actions/checkout@v4
      with:
        submodules: recursive
        repository: duckduckgo/shared-web-tests
        path: tmp/shared-web-tests
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and run tests
      run: |
        PROJECT_ROOT="$(pwd)"
        . iOS/scripts/shared_web_tests.sh

    - name: Upload logs when workflow failed
      uses: actions/upload-artifact@v4
      if: failure() || cancelled()
      with:
        name: BuildLogs
        path: |
            tmp/test_out_*.log
        retention-days: 7

  create-asana-task:
    name: Create Asana Task
    needs: [shared-web-tests]

    if: failure()

    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4
      - name: Create Asana task when workflow failed
        uses: duckduckgo/native-github-asana-sync@v1.1
        with:
          action: create-asana-task
          asana-pat: ${{ secrets.ASANA_ACCESS_TOKEN }}
          asana-project: ${{ vars.APPLE_CI_FAILING_TESTS_PROJECT_ID }}
          asana-section: ${{ vars.APPLE_CI_FAILING_TESTS_IOS_SHARED_WEB_TESTS_SECTION_ID }}
          asana-task-name: GH Workflow Failure - iOS Shared Web Tests
          asana-task-description: The iOS Shared Web Tests workflow has failed. See https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
